services:
  - type: web
    name: glassyolo
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m gunicorn app:app --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production 
